# Generated by Django 4.0.5 on 2022-07-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='nameOfSheet',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
