# Generated by Django 4.0.5 on 2022-08-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupApp', '0004_sheet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='createrEmail',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
    ]
