# Generated by Django 4.0.5 on 2022-08-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupApp', '0005_sheet_createremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerEmail', models.EmailField(max_length=254)),
                ('userEmail', models.EmailField(max_length=254)),
                ('sheetId', models.IntegerField()),
                ('sheetPermission', models.BooleanField(default=False)),
            ],
        ),
    ]
