# Generated by Django 4.0.5 on 2022-08-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupApp', '0006_sheetpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetpermission',
            name='sheetName',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
