# Generated by Django 4.0.5 on 2022-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupApp', '0007_sheetpermission_sheetname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetpermission',
            name='giveAccess',
            field=models.BooleanField(default=True),
        ),
    ]
